# Generated by Django 4.0.3 on 2022-03-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
